(* Read a graph from a Team Classementfile,
 * Write a graph. *)

open Graph

type path = string

(* Read a Team Classement file, and produce a graph 
   Args: path to the file
   Return: String graph*)
val from_file: path -> string graph

(* Write a graph in a file with a specific format
   Args: path to the file -> String graph
   Return: unit *)
val write_file: path -> string graph -> unit

(* Export a graph into a file in the dot format in oder to be displayed
   Args: int graph -> path 
   Return:  unit *)
val export: int graph -> path -> unit ;;

(* The format of files is compatible with the files generated by:
   https://www-m9.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)
